version: "3"

services:
  haproxy:
    image: haproxy:2.3.4
    container_name: haproxy
    ports:
      - "80:8080"
    volumes:
      - ./data/:/usr/local/etc/haproxy
    depends_on:
      - server1
      - server2
      - server3
      - server4

  server1:
    build: 
      context: ./api
    container_name: api1
    ports:
      - "8081:8080"

  server2:
    build: 
      context: ./api
    container_name: api2
    ports:
      - "8082:8080"

  server3:
    build: 
      context: ./api
    container_name: api3
    ports:
      - "8083:8080" 

  server4:
    build: 
      context: ./api
    container_name: api4
    ports:
      - "8084:8080"
   
