version: "3"

services:
  haproxy:
    image: haproxy:2.3.4
    container_name: haproxy
    volumes:
      - ./data/:/usr/local/etc/haproxy
    depends_on:
      - server1
      - server2
      - server3
      - server4

  server1:
    image: api:v1.0.0
    container_name: api1

  server2:
    image: api:v1.0.0
    container_name: api2

  server3:
    image: api:v1.0.0
    container_name: api3

  server4:
    image: api:v1.0.0
    container_name: api4
   